# -*- coding: utf-8 -*-
"""1201C

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/128zUbxQOXjKsMPaKuynqvUOkRaQVc3gB
"""

import sys

def check(x, a, n, k):
    moves = 0
    for i in range(n // 2, n):
        if x > a[i]:
            moves += x - a[i]
            if moves > k:
                return False
    return moves <= k


n, k = map(int, input().split())
a = list(map(int, input().split()))
a.sort()

small = 1
big = 2 * 10**9

while small != big:
    mid = (small + big + 1) // 2
    if check(mid, a, n, k):
        small = mid
    else:
        big = mid - 1

print(small)