# -*- coding: utf-8 -*-
"""1324D

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RpMh3IocNrII5LWY9nVhUNAt48x8tdZT
"""

import sys
import bisect


n = int(input())
a = list(map(int, input().split()))
b = list(map(int, input().split()))

# Вычисление разницы между элементами массивов
c = [a[i] - b[i] for i in range(n)]
c.sort()

ans = 0
for i in range(n):
  if c[i] <= 0:
      continue
  # Находим первый элемент, который больше -c[i]
  pos = bisect.bisect_left(c, -c[i] + 1)
  ans += i - pos

print(ans)