# -*- coding: utf-8 -*-
"""1328B

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pkg5HsURljJ9T_w9llH2OzSs5mou5DgI
"""

t = int(input())
for _ in range(t):
    n, k = map(int, input().split())
    s = ['a'] * n
    for i in range(n - 2, -1, -1):
        if k <= (n - i - 1):
            s[i] = 'b'
            s[n - k] = 'b'
            print(''.join(s))
            break
        k -= (n - i - 1)