# -*- coding: utf-8 -*-
"""1343с

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15k2lF_eEvtoKFKo1P0JOLffnGkK8qL7r
"""

import sys

def solve():
    input = sys.stdin.read
    data = input().split()
    idx = 0
    t = int(data[idx])
    idx += 1
    for _ in range(t):
        n = int(data[idx])
        idx += 1
        a = list(map(int, data[idx:idx + n]))
        idx += n

        sum = 0
        i = 0
        while i < n:
            current = a[i]
            j = i
            while j < n and (a[i] > 0) == (a[j] > 0):
                current = max(current, a[j])
                j += 1
            sum += current
            i = j
        print(sum)

solve()