# -*- coding: utf-8 -*-
"""1360C

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1psRt-3Qilyyde4GBl2XQqdFjW8TFTpoF
"""

t = int(input())
for _ in range(t):
  j = 0
  n = int(input())
  a = list(map(int,input().split()))
  a = sorted(a)
  for i in range(len(a)-1):
    if a[i]/2 == a[i+1]/2 or abs(a[i]-a[i+1]) == 1:
      print('YES')
      j += 1
      break
  if j == 0:
    print('NO')

t = int(input())
for _ in range(t):
    n = int(input())
    a = list(map(int, input().split()))
    even = 0
    odd = 0
    for num in a:
        if num % 2 == 0:
            even += 1
        else:
            odd += 1
    # Если количество четных и нечетных оба четны, то YES
    if even % 2 == 0 and odd % 2 == 0:
        print("YES")
    else:
        # Ищем пару (x, y), где x и y разной четности и |x - y| = 1
        a_sorted = sorted(a)
        found = False
        for i in range(n - 1):
            if (a_sorted[i] % 2 != a_sorted[i + 1] % 2) and (abs(a_sorted[i] - a_sorted[i + 1]) == 1):
                found = True
                break
        print("YES" if found else "NO")