# -*- coding: utf-8 -*-
"""1364A

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FA1m2tQL2C09DZFP8AyAjhViFgEJrRQX
"""

import sys

def main():
    input = sys.stdin.read().split()
    ptr = 0
    t = int(input[ptr])
    ptr += 1
    for _ in range(t):
        n = int(input[ptr])
        x = int(input[ptr + 1])
        ptr += 2
        a = list(map(int, input[ptr:ptr + n]))
        ptr += n

        sum_total = 0
        l = -1
        r = -1

        for i in range(n):
            if a[i] % x != 0:
                if l == -1:
                    l = i
                r = i
            sum_total += a[i]

        if sum_total % x != 0:
            print(n)
        elif l == -1:
            print(-1)
        else:
            print(n - min(l + 1, n - r))

if __name__ == "__main__":
    main()