# -*- coding: utf-8 -*-
"""1366A

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dxB6WzFkfFuRT4uvIG3IhxiVIGUI66IC
"""

t = int(input())
for _ in range(t):
  a,b = map(int,input().split())
  print(min(a,b,(a+b)//3))