# -*- coding: utf-8 -*-
"""1420B

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11WeG3HOQ_Go8yR_lbQtbA3IQJCIqF4k9
"""

import sys
import random

def main():
    input = sys.stdin.read
    data = input().split()
    idx = 0
    t = int(data[idx])
    idx += 1
    for _ in range(t):
        n = int(data[idx])
        idx += 1
        a = list(map(int, data[idx:idx + n]))
        idx += n

        ans = 0
        for j in range(29, -1, -1):
            cnt = 0
            lower = 1 << j
            upper = 1 << (j + 1)
            for num in a:
                if lower <= num < upper:
                    cnt += 1
            ans += cnt * (cnt - 1) // 2

        print(ans)

if __name__ == "__main__":
    main()