# -*- coding: utf-8 -*-
"""1669F

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3eqzn9HuSfdoneWXMbN-0NdteSqFJex
"""

import sys

def solve():
    input = sys.stdin.read().split()
    ptr = 0
    t = int(input[ptr])
    ptr += 1
    results = []
    for _ in range(t):
        n = int(input[ptr])
        ptr += 1
        w = list(map(int, input[ptr:ptr + n]))
        ptr += n

        left = 0
        right = n - 1
        sum_left = 0
        sum_right = 0
        max_candies = 0
        count = 0

        while left <= right:
            if sum_left < sum_right:
                sum_left += w[left]
                left += 1
                count += 1
            elif sum_left > sum_right:
                sum_right += w[right]
                right -= 1
                count += 1
            else:
                max_candies = count
                sum_left += w[left]
                left += 1
                count += 1

        if sum_left == sum_right:
            max_candies = count

        results.append(max_candies)

    print('\n'.join(map(str, results)))

solve()