# -*- coding: utf-8 -*-
"""1791E

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ECJWj8IREuQ6DFbkKrmFJC8ehYIE6YrQ
"""

import sys

def main():
    t = int(sys.stdin.readline())
    for _ in range(t):
        n = int(sys.stdin.readline())
        a = list(map(int, sys.stdin.readline().split()))
        sum_val = 0
        negs = 0
        for i in range(n):
            if a[i] < 0:
                negs += 1
                a[i] = -a[i]
            sum_val += a[i]
        a.sort()
        if negs % 2 == 1:
            sum_val -= 2 * a[0]
        print(sum_val)

if __name__ == "__main__":
    main()