# -*- coding: utf-8 -*-
"""1873E

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dive8wj4uee3qnxBESjQFkOAylRZ2oNM
"""

import sys

def solve():
    n, x = map(int, sys.stdin.readline().split())
    a = list(map(int, sys.stdin.readline().split()))
    lo = 0
    hi = 2_000_000_007
    while lo < hi:
        mid = lo + (hi - lo + 1) // 2
        tot = 0
        for num in a:
            tot += max(mid - num, 0)
        if tot <= x:
            lo = mid
        else:
            hi = mid - 1
    print(lo)

def main():
    input = sys.stdin.read
    data = input().split()
    idx = 0
    tt = int(data[idx])
    idx += 1
    for _ in range(tt):
        n = int(data[idx])
        x = int(data[idx + 1])
        idx += 2
        a = list(map(int, data[idx:idx + n]))
        idx += n
        # Now solve for this test case
        lo = 0
        hi = 2_000_000_007
        while lo < hi:
            mid = lo + (hi - lo + 1) // 2
            tot = 0
            for num in a:
                tot += max(mid - num, 0)
            if tot <= x:
                lo = mid
            else:
                hi = mid - 1
        print(lo)

if __name__ == "__main__":
    main()