# -*- coding: utf-8 -*-
"""1914D

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbpbFXT9a8gcLZnhF3g8uG1sybU4pqoG
"""

t = int(input())
for _ in range(t):
    n = int(input())
    a = list(map(int, input().split()))
    b = list(map(int, input().split()))
    c = list(map(int, input().split()))

    # Создадим списки: (значение, индекс) для каждого массива
    A = [(a[i], i) for i in range(n)]
    B = [(b[i], i) for i in range(n)]
    C = [(c[i], i) for i in range(n)]

    # Сортируем по убыванию значения
    A.sort(reverse=True, key=lambda x: x[0])
    B.sort(reverse=True, key=lambda x: x[0])
    C.sort(reverse=True, key=lambda x: x[0])

    # Берём топ-3 из каждого (или меньше, если n < 3)
    topA = A[:3]
    topB = B[:3]
    topC = C[:3]

    best = 0

    # Перебираем все комбинации из топ-3 каждого
    for val_a, i in topA:
        for val_b, j in topB:
            for val_c, k in topC:
                if i != j and i != k and j != k:
                    total = val_a + val_b + val_c
                    if total > best:
                        best = total

    print(best)