# -*- coding: utf-8 -*-
"""479C

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Me8DNusR3euWIlFA63wG8b389jH_5FiN
"""

n = int(input())
a = []
for _ in range(n):
  c = list(map(int,input().split()))
  a.append(c)
a.sort()  # a, - список кортежей, где первый элемент - фактическая сдача экзамена,
          # а второй элемент - досрочная сдача
best = -1
for item in a:
    if best <= item[1]:
        best = item[1]
    else:
        best = item[0]
print(best)