# -*- coding: utf-8 -*-
"""545С

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sq-RhG62u9gUuL_EJP48MSjW5lh_oVu8
"""

n = int(input())
trees = []
for _ in range(n):
    x, h = map(int, input().split())
    trees.append((x, h))

# Деревья уже отсортированы по x — по условию задачи

if n == 1:
    print(1)
    exit()

count = 0
last_occupied = -10**18  # очень маленькое число — "последняя занятая позиция справа"

for i in range(n):
    x, h = trees[i]

    # Пробуем повалить влево
    if x - h > last_occupied:
        count += 1
        last_occupied = x  # дерево упало влево → занимает [x-h, x], значит, последняя занятая точка — x
    else:
        # Влево нельзя — пробуем вправо (если не последнее дерево — проверяем следующее)
        if i == n - 1:
            # Последнее дерево — всегда можно вправо
            count += 1
            # last_occupied = x + h  # можно обновить, но дальше никого нет — не обязательно
        else:
            next_x = trees[i + 1][0]
            if x + h < next_x:
                count += 1
                last_occupied = x + h  # дерево упало вправо
            else:
                # Нельзя ни влево, ни вправо — оставляем стоять
                last_occupied = x  # дерево стоит — занимает только точку x

print(count)