# -*- coding: utf-8 -*-
"""270A

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1No17_9n12CqWhH0skkpClSX5PmWPprC4
"""

t = int(input())
for _ in range(t):
    a = int(input())
    if 360 % (180 - a) == 0 and (360 // (180 - a)) >= 3:
        print("YES")
    else:
        print("NO")