# -*- coding: utf-8 -*-
"""313B

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ep49UWOdyk2nN64jq6COYPG7ImAvsTat
"""

s = input().strip()
n = len(s)
prefix = [0] * (n + 1)

for i in range(1, n):
    prefix[i] = prefix[i-1] + (1 if s[i-1] == s[i] else 0)

m = int(input())
for _ in range(m):
    l, r = map(int, input().split())
    print(prefix[r-1] - prefix[l-1])